require("caplox.configs.lsp")
require("caplox.configs.cmp")
require("caplox.configs.lint")
require("caplox.configs.mason")
require("caplox.configs.nvim-dap")
require("caplox.configs.whichkey")
require("caplox.configs.luasnip")
