local wk = require("which-key")

wk.register({
    { ";",          desc = "Command Mode" },
    { "<C-n>",      desc = "Open Parent Directory" },
    { "<F5>",       desc = "Run Code" },
    { "<Leader>/",  desc = "Comment" },
    { "<Leader>c",  group = "Copilot" },
    { "<Leader>cd", desc = "Disable" },
    { "<Leader>ce", desc = "Enable" },
    { "<Leader>d",  group = "Debug" },
    { "<Leader>db", desc = "Toggle Breakpoint" },
    { "<Leader>di", desc = "Step Into" },
    { "<Leader>dn", desc = "Step Over" },
    { "<Leader>do", desc = "Step Out" },
    { "<Leader>dq", desc = "Quit" },
    { "<Leader>dt", desc = "Toggle Debugger" },
    { "<Leader>f",  group = "Telescope" },
    { "<Leader>ff", desc = "Find files" },
    { "<Leader>fg", desc = "Live grep" },
    { "<Leader>g",  group = "Git" },
    { "<Leader>ga", desc = "Add" },
    { "<Leader>gb", desc = "Blame" },
    { "<Leader>gc", desc = "Commit" },
    { "<Leader>gd", desc = "Diff" },
    { "<Leader>gl", desc = "Log" },
    { "<Leader>go", desc = "Overview" },
    { "<Leader>gp", desc = "Pull" },
    { "<Leader>gu", desc = "Unstage All" },
    { "<Leader>l",  group = "LaTeX" },
    { "<Leader>le", desc = "Errors" },
    { "<Leader>ll", desc = "Compile" },
    { "<Leader>p",  desc = "Paste to Clipboard" },
    { "<Leader>y",  desc = "Yank to Clipboard" },
})
