#!/bin/bash

awk -F"[][]" '/Left:/ { print $2 }' <(amixer sget Master)

case $button in
    1) amixer -q sset Master 5%+ ;;
    2) amixer -q sset Master toggle ;;
    3) amixer -q sset Master 5%- ;;
esac
