#!/bin/bash

# Capture volume and state (on/off)
volume=$(amixer sget Master | awk -F'[][]' '/Left:/ { print $2 }')
state=$(amixer sget Master | awk -F'[][]' '/Left:/ { print $4; exit }')

# Only show the state if it's off
if [ "$state" == "off" ]; then
    echo "$volume ($state)"
else
    echo "$volume"
fi
