#!/bin/bash

sink=$(pactl get-default-sink)
volume=$(pactl get-sink-volume "$sink" | awk '{print $5; exit}')
mute=$(pactl get-sink-mute "$sink" | awk '{print $2}')

if [ "$mute" = "yes" ]; then
    echo "$volume (off)"
else
    echo "$volume"
fi
