[general]
import = [
    "theme.toml",
]

[window]
opacity = 0.8

[font]
# Normal automatically adjusts others
normal = { family = "FiraCode Nerd Font", style = "Regular"}
size = 15
offset = {x = 0, y = 1}

[mouse]
hide_when_typing = true

[keyboard]
bindings = [{key = "Enter", mods = "Super | Shift", action = "SpawnNewInstance"}]
