[general]
import = [
    "theme.toml",
    # extra.toml is for system specific options
    "extra.toml",
]

[window]
opacity = 0.8

[font]
# Normal automatically adjusts others
normal = { family = "FiraCode Nerd Font", style = "Regular"}

[mouse]
hide_when_typing = true

[keyboard]
bindings = [{key = "Enter", mods = "Super | Shift", action = "SpawnNewInstance"}]
